import "./App.css";
import { Routes, Route } from "react-router-dom";
import Landing from "../components/Landing/Landing";
import Home from "../components/Home/Home";
import Card from "../components/Card/Card";
import Cards from "../components/Cards/Cards";

const data = [
  {
    id: 1,
    name: "bulbasaur",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/1.png",
    types: ["grass", "poison"],
    hp: 45,
    attack: 49,
    defense: 49,
    speed: 45,
    height: 7,
    weight: 69,
  },
  {
    id: 2,
    name: "ivysaur",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/2.png",
    types: ["grass", "poison"],
    hp: 60,
    attack: 62,
    defense: 63,
    speed: 60,
    height: 10,
    weight: 130,
  },
  {
    id: 3,
    name: "venusaur",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/3.png",
    types: ["grass", "poison"],
    hp: 80,
    attack: 82,
    defense: 83,
    speed: 80,
    height: 20,
    weight: 1000,
  },
  {
    id: 4,
    name: "charmander",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/4.png",
    types: ["fire"],
    hp: 39,
    attack: 52,
    defense: 43,
    speed: 65,
    height: 6,
    weight: 85,
  },
  {
    id: 5,
    name: "charmeleon",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/5.png",
    types: ["fire"],
    hp: 58,
    attack: 64,
    defense: 58,
    speed: 80,
    height: 11,
    weight: 190,
  },
  {
    id: 6,
    name: "charizard",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/6.png",
    types: ["fire", "flying"],
    hp: 78,
    attack: 84,
    defense: 78,
    speed: 100,
    height: 17,
    weight: 905,
  },
  {
    id: 7,
    name: "squirtle",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/7.png",
    types: ["water"],
    hp: 44,
    attack: 48,
    defense: 65,
    speed: 43,
    height: 5,
    weight: 90,
  },
  {
    id: 8,
    name: "wartortle",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/8.png",
    types: ["water"],
    hp: 59,
    attack: 63,
    defense: 80,
    speed: 58,
    height: 10,
    weight: 225,
  },
  {
    id: 9,
    name: "blastoise",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/9.png",
    types: ["water"],
    hp: 79,
    attack: 83,
    defense: 100,
    speed: 78,
    height: 16,
    weight: 855,
  },
  {
    id: 10,
    name: "caterpie",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/10.png",
    types: ["bug"],
    hp: 45,
    attack: 30,
    defense: 35,
    speed: 45,
    height: 3,
    weight: 29,
  },
  {
    id: 11,
    name: "metapod",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/11.png",
    types: ["bug"],
    hp: 50,
    attack: 20,
    defense: 55,
    speed: 30,
    height: 7,
    weight: 99,
  },
  {
    id: 12,
    name: "butterfree",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/12.png",
    types: ["bug", "flying"],
    hp: 60,
    attack: 45,
    defense: 50,
    speed: 70,
    height: 11,
    weight: 320,
  },
  {
    id: 13,
    name: "weedle",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/13.png",
    types: ["bug", "poison"],
    hp: 40,
    attack: 35,
    defense: 30,
    speed: 50,
    height: 3,
    weight: 32,
  },
  {
    id: 14,
    name: "kakuna",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/14.png",
    types: ["bug", "poison"],
    hp: 45,
    attack: 25,
    defense: 50,
    speed: 35,
    height: 6,
    weight: 100,
  },
  {
    id: 15,
    name: "beedrill",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/15.png",
    types: ["bug", "poison"],
    hp: 65,
    attack: 90,
    defense: 40,
    speed: 75,
    height: 10,
    weight: 295,
  },
  {
    id: 16,
    name: "pidgey",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/16.png",
    types: ["normal", "flying"],
    hp: 40,
    attack: 45,
    defense: 40,
    speed: 56,
    height: 3,
    weight: 18,
  },
  {
    id: 17,
    name: "pidgeotto",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/17.png",
    types: ["normal", "flying"],
    hp: 63,
    attack: 60,
    defense: 55,
    speed: 71,
    height: 11,
    weight: 300,
  },
  {
    id: 18,
    name: "pidgeot",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/18.png",
    types: ["normal", "flying"],
    hp: 83,
    attack: 80,
    defense: 75,
    speed: 101,
    height: 15,
    weight: 395,
  },
  {
    id: 19,
    name: "rattata",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/19.png",
    types: ["normal"],
    hp: 30,
    attack: 56,
    defense: 35,
    speed: 72,
    height: 3,
    weight: 35,
  },
  {
    id: 20,
    name: "raticate",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/20.png",
    types: ["normal"],
    hp: 55,
    attack: 81,
    defense: 60,
    speed: 97,
    height: 7,
    weight: 185,
  },
  {
    id: 21,
    name: "spearow",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/21.png",
    types: ["normal", "flying"],
    hp: 40,
    attack: 60,
    defense: 30,
    speed: 70,
    height: 3,
    weight: 20,
  },
  {
    id: 22,
    name: "fearow",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/22.png",
    types: ["normal", "flying"],
    hp: 65,
    attack: 90,
    defense: 65,
    speed: 100,
    height: 12,
    weight: 380,
  },
  {
    id: 23,
    name: "ekans",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/23.png",
    types: ["poison"],
    hp: 35,
    attack: 60,
    defense: 44,
    speed: 55,
    height: 20,
    weight: 69,
  },
  {
    id: 24,
    name: "arbok",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/24.png",
    types: ["poison"],
    hp: 60,
    attack: 95,
    defense: 69,
    speed: 80,
    height: 35,
    weight: 650,
  },
  {
    id: 25,
    name: "pikachu",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/25.png",
    types: ["electric"],
    hp: 35,
    attack: 55,
    defense: 40,
    speed: 90,
    height: 4,
    weight: 60,
  },
  {
    id: 26,
    name: "raichu",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/26.png",
    types: ["electric"],
    hp: 60,
    attack: 90,
    defense: 55,
    speed: 110,
    height: 8,
    weight: 300,
  },
  {
    id: 27,
    name: "sandshrew",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/27.png",
    types: ["ground"],
    hp: 50,
    attack: 75,
    defense: 85,
    speed: 40,
    height: 6,
    weight: 120,
  },
  {
    id: 28,
    name: "sandslash",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/28.png",
    types: ["ground"],
    hp: 75,
    attack: 100,
    defense: 110,
    speed: 65,
    height: 10,
    weight: 295,
  },
  {
    id: 29,
    name: "nidoran-f",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/29.png",
    types: ["poison"],
    hp: 55,
    attack: 47,
    defense: 52,
    speed: 41,
    height: 4,
    weight: 70,
  },
  {
    id: 30,
    name: "nidorina",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/30.png",
    types: ["poison"],
    hp: 70,
    attack: 62,
    defense: 67,
    speed: 56,
    height: 8,
    weight: 200,
  },
  {
    id: 31,
    name: "nidoqueen",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/31.png",
    types: ["poison", "ground"],
    hp: 90,
    attack: 92,
    defense: 87,
    speed: 76,
    height: 13,
    weight: 600,
  },
  {
    id: 32,
    name: "nidoran-m",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/32.png",
    types: ["poison"],
    hp: 46,
    attack: 57,
    defense: 40,
    speed: 50,
    height: 5,
    weight: 90,
  },
  {
    id: 33,
    name: "nidorino",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/33.png",
    types: ["poison"],
    hp: 61,
    attack: 72,
    defense: 57,
    speed: 65,
    height: 9,
    weight: 195,
  },
  {
    id: 34,
    name: "nidoking",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/34.png",
    types: ["poison", "ground"],
    hp: 81,
    attack: 102,
    defense: 77,
    speed: 85,
    height: 14,
    weight: 620,
  },
  {
    id: 35,
    name: "clefairy",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/35.png",
    types: ["fairy"],
    hp: 70,
    attack: 45,
    defense: 48,
    speed: 35,
    height: 6,
    weight: 75,
  },
  {
    id: 36,
    name: "clefable",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/36.png",
    types: ["fairy"],
    hp: 95,
    attack: 70,
    defense: 73,
    speed: 60,
    height: 13,
    weight: 400,
  },
  {
    id: 37,
    name: "vulpix",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/37.png",
    types: ["fire"],
    hp: 38,
    attack: 41,
    defense: 40,
    speed: 65,
    height: 6,
    weight: 99,
  },
  {
    id: 38,
    name: "ninetales",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/38.png",
    types: ["fire"],
    hp: 73,
    attack: 76,
    defense: 75,
    speed: 100,
    height: 11,
    weight: 199,
  },
  {
    id: 39,
    name: "jigglypuff",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/39.png",
    types: ["normal", "fairy"],
    hp: 115,
    attack: 45,
    defense: 20,
    speed: 20,
    height: 5,
    weight: 55,
  },
  {
    id: 40,
    name: "wigglytuff",
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/home/40.png",
    types: ["normal", "fairy"],
    hp: 140,
    attack: 70,
    defense: 45,
    speed: 45,
    height: 10,
    weight: 120,
  },
];

function App() {
  return (
    <div className="App">
      <Routes>
        <Route path="/" element={<Landing />} />
        <Route path="/home" element={<Home />} />
        <Route path="/card" element={<Card id={1} name="Bulbasaur" />} />
        <Route path="/cards" element={<Cards pokemons={data} />} />
      </Routes>
    </div>
  );
}

export default App;
